"use client";

import { useEffect, useMemo, useState } from "react";
import { Bell, Bookmark, CalendarDays, Check, Clock3, Compass, Flag, Footprints, Leaf, LoaderCircle, Lock, MapPin, Mountain, Navigation, Plus, ShieldCheck, Star, Trees, Trophy, UserRound, Users, X } from "lucide-react";
import type { User } from "@supabase/supabase-js";
import { ExploreMap, type RouteCoordinate } from "./explore-map";
import { createEvent, createGroup, createPlace, createPost, joinGroup, leaveGroup, loadAchievements, loadEnvironmentReports, loadNotifications, markNotificationsRead, respondToEvent, toggleReportConfirmation, updateProfile } from "../services/community";
import { addTrailReview, createTrail, saveTrail } from "../services/trails";
import type { Achievement, AdventureGroup, AppNotification, EnvironmentReport, OutdoorEvent, Profile, Trail } from "../types/domain";

type Notify = (text: string) => void;
type CloseProps = { onClose: () => void; notify: Notify };

function ModalShell({ title, subtitle, icon: Icon, onClose, children }: CloseProps & { title: string; subtitle: string; icon: typeof Compass; children: React.ReactNode }) {
  return <div className="modal-layer auth-layer" role="dialog" aria-modal="true" aria-label={title}><section className="feature-panel"><header className="feature-panel-header"><span><Icon size={22} /></span><div><h2>{title}</h2><p>{subtitle}</p></div><button onClick={onClose} aria-label="Fechar"><X size={20} /></button></header>{children}</section></div>;
}

function CurrentLocation({ value, onChange, notify }: { value: RouteCoordinate | null; onChange: (value: RouteCoordinate) => void; notify: Notify }) {
  const [loading, setLoading] = useState(false);
  function locate() {
    if (!navigator.geolocation) { notify("GPS não disponível neste dispositivo"); return; }
    setLoading(true);
    navigator.geolocation.getCurrentPosition(({ coords }) => { onChange([coords.longitude, coords.latitude]); setLoading(false); }, () => { notify("Autorize o GPS para capturar a localização"); setLoading(false); }, { enableHighAccuracy: true, maximumAge: 5_000, timeout: 15_000 });
  }
  return <button type="button" className={`location-picker ${value ? "ready" : ""}`} onClick={locate}>{loading ? <LoaderCircle className="animate-spin" size={17} /> : value ? <Check size={17} /> : <Navigation size={17} />}<span><strong>{value ? "Localização capturada" : "Usar minha localização"}</strong><small>{value ? `${value[1].toFixed(5)}, ${value[0].toFixed(5)}` : "Necessária para aparecer no mapa"}</small></span></button>;
}

export function CreateTrailPanel({ user, onClose, notify, onCreated }: CloseProps & { user: User; onCreated: (trail: Trail) => void }) {
  const [coordinate, setCoordinate] = useState<RouteCoordinate | null>(null);
  const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!coordinate) { notify("Capture a localização inicial da trilha"); return; }
    const form = new FormData(event.currentTarget); setLoading(true);
    try {
      const trail = await createTrail(user.id, { name: String(form.get("name")), description: String(form.get("description")), location: String(form.get("location")), city: String(form.get("city")), state: String(form.get("state")), distanceKm: Number(form.get("distance")), elevationGainM: Number(form.get("elevation")), difficulty: String(form.get("difficulty")), durationMinutes: Number(form.get("duration")), latitude: coordinate[1], longitude: coordinate[0], terrainType: String(form.get("terrain")), bestSeason: String(form.get("season")), waterSource: form.get("water") === "on", cellSignal: String(form.get("signal")), campingArea: form.get("camping") === "on", parking: form.get("parking") === "on", petsAllowed: form.get("pets") === "on", guideRequired: form.get("guide") === "on" });
      notify("Trilha cadastrada e enviada para validação da comunidade"); onCreated(trail); onClose();
    } catch (error) { notify(error instanceof Error ? error.message : "Falha ao cadastrar trilha"); } finally { setLoading(false); }
  }
  return <ModalShell title="Cadastrar trilha" subtitle="Documente o caminho com responsabilidade." icon={Footprints} onClose={onClose} notify={notify}><form className="feature-form" onSubmit={submit}><label>Nome da trilha<input name="name" required minLength={3} maxLength={100} placeholder="Ex.: Trilha do Pico da Serra" /></label><label>Descrição<textarea name="description" maxLength={3000} placeholder="Acesso, terreno, cuidados e pontos de referência." /></label><div className="field-row"><label>Cidade<input name="city" /></label><label>Estado<input name="state" maxLength={2} /></label></div><label>Localização/região<input name="location" placeholder="Parque, serra ou distrito" /></label><div className="field-row"><label>Distância (km)<input name="distance" type="number" min="0" step="0.1" required /></label><label>Elevação (m)<input name="elevation" type="number" min="0" step="1" required /></label></div><div className="field-row"><label>Duração (min)<input name="duration" type="number" min="0" step="5" required /></label><label>Dificuldade<select name="difficulty" defaultValue="moderate"><option value="easy">Fácil</option><option value="moderate">Moderada</option><option value="hard">Difícil</option><option value="expert">Especialista</option></select></label></div><div className="field-row"><label>Terreno<input name="terrain" placeholder="Terra, rocha…" /></label><label>Melhor época<input name="season" placeholder="Ano todo" /></label></div><label>Sinal de celular<input name="signal" placeholder="Bom, parcial ou inexistente" /></label><div className="check-grid"><label><input type="checkbox" name="water" /> Fonte de água</label><label><input type="checkbox" name="camping" /> Área de camping</label><label><input type="checkbox" name="parking" /> Estacionamento</label><label><input type="checkbox" name="pets" /> Permite animais</label><label><input type="checkbox" name="guide" /> Guia necessário</label></div><CurrentLocation value={coordinate} onChange={setCoordinate} notify={notify} /><button className="auth-submit" disabled={loading}>{loading ? "CADASTRANDO…" : "CADASTRAR TRILHA"}</button><p className="responsibility-note"><ShieldCheck size={15} /> Não cadastre acessos proibidos, propriedades privadas sem autorização ou rotas que coloquem pessoas em risco.</p></form></ModalShell>;
}

export function TrailDetailPanel({ trail, user, onClose, notify, onStart }: CloseProps & { trail: Trail; user: User | null; onStart: () => void }) {
  const [reviewing, setReviewing] = useState(false); const [saved, setSaved] = useState(false); const [loading, setLoading] = useState(false);
  const route = trail.route_geojson?.coordinates ?? [];
  async function save() { if (!user) { notify("Entre para salvar trilhas"); return; } setLoading(true); try { await saveTrail(user.id, trail.id); setSaved(true); notify("Trilha salva em Quero conhecer"); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao salvar"); } finally { setLoading(false); } }
  async function submitReview(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!user) { notify("Entre para avaliar esta trilha"); return; } const form = new FormData(event.currentTarget); setLoading(true); try { await addTrailReview(user.id, trail.id, Number(form.get("rating")), String(form.get("review"))); setReviewing(false); notify("Avaliação publicada"); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao avaliar"); } finally { setLoading(false); } }
  const info = [{ label: "Terreno", value: trail.terrain_type }, { label: "Melhor época", value: trail.best_season }, { label: "Sinal", value: trail.cell_signal }, { label: "Água", value: trail.water_source === null ? null : trail.water_source ? "Disponível" : "Não informado" }, { label: "Camping", value: trail.camping_area === null ? null : trail.camping_area ? "Sim" : "Não" }, { label: "Estacionamento", value: trail.parking === null ? null : trail.parking ? "Sim" : "Não" }, { label: "Animais", value: trail.pets_allowed === null ? null : trail.pets_allowed ? "Permitidos" : "Não" }, { label: "Guia", value: trail.guide_required === null ? null : trail.guide_required ? "Necessário" : "Opcional" }].filter((item) => item.value !== null && item.value !== "");
  return <ModalShell title={trail.name} subtitle={`${trail.city ?? trail.location ?? "Brasil"}${trail.state ? `, ${trail.state}` : ""}`} icon={Mountain} onClose={onClose} notify={notify}><div className="trail-detail"><ExploreMap compact route={route} markers={trail.longitude !== null && trail.latitude !== null ? [{ id: trail.id, label: trail.name, coordinate: [trail.longitude, trail.latitude] }] : []} /><div className="trail-detail-metrics"><div><strong>{(trail.distance_m / 1000).toFixed(1)} km</strong><small>Distância</small></div><div><strong>+{trail.elevation_gain} m</strong><small>Elevação</small></div><div><strong>{trail.estimated_duration ? `${Math.floor(trail.estimated_duration / 3600)}h${Math.round((trail.estimated_duration % 3600) / 60).toString().padStart(2, "0")}` : "—"}</strong><small>Duração</small></div><div><strong>{trail.difficulty === "easy" ? "Fácil" : trail.difficulty === "moderate" ? "Moderada" : trail.difficulty === "hard" ? "Difícil" : "Especialista"}</strong><small>Dificuldade</small></div></div>{trail.verified ? <div className="verified-note"><ShieldCheck size={17} /> Informações verificadas pela comunidade</div> : <div className="review-note"><Flag size={17} /> Cadastro comunitário aguardando validação</div>}<p>{trail.description || "A comunidade ainda não adicionou uma descrição detalhada para esta trilha."}</p>{info.length ? <div className="trail-info-grid">{info.map((item) => <div key={item.label}><small>{item.label}</small><strong>{item.value}</strong></div>)}</div> : null}<div className="detail-actions"><button className="secondary-button" onClick={() => void save()} disabled={loading}><Bookmark size={17} fill={saved ? "currentColor" : "none"} />{saved ? "SALVA" : "SALVAR"}</button><button className="primary-button" onClick={() => { onStart(); onClose(); }}><Navigation size={17} /> INICIAR TRILHA</button></div><button className="review-trigger" onClick={() => setReviewing((value) => !value)}><Star size={17} /> Avaliar condições desta trilha</button>{reviewing ? <form className="inline-review" onSubmit={submitReview}><select name="rating" defaultValue="5"><option value="5">5 — Excelente</option><option value="4">4 — Muito boa</option><option value="3">3 — Regular</option><option value="2">2 — Ruim</option><option value="1">1 — Perigosa/precisa atenção</option></select><textarea name="review" maxLength={1000} placeholder="Conte como estavam o acesso, terreno e sinalização." /><button className="auth-submit">PUBLICAR AVALIAÇÃO</button></form> : null}</div></ModalShell>;
}

export function CommunityCreatePanel({ user, groups, mode, onClose, notify, onCreated }: CloseProps & { user: User; groups: AdventureGroup[]; mode: "group" | "event"; onCreated: () => void }) {
  const [loading, setLoading] = useState(false);
  const [minimumDate] = useState(() => new Date(Date.now() + 3_600_000).toISOString().slice(0, 16));
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setLoading(true); try { if (mode === "group") await createGroup(user.id, { name: String(form.get("name")), description: String(form.get("description")), city: String(form.get("city")), state: String(form.get("state")), privacy: String(form.get("privacy")) as "public" | "private" }); else await createEvent(user.id, { groupId: String(form.get("group_id") || "") || undefined, name: String(form.get("name")), description: String(form.get("description")), startAt: String(form.get("start_at")), meetingPoint: String(form.get("meeting_point")), difficulty: String(form.get("difficulty")), distanceKm: Number(form.get("distance")), maxParticipants: Number(form.get("max_participants")), equipment: String(form.get("equipment")) }); notify(mode === "group" ? "Grupo criado com sucesso" : "Evento publicado com sucesso"); onCreated(); onClose(); } catch (error) { notify(error instanceof Error ? error.message : "Não foi possível concluir"); } finally { setLoading(false); } }
  return <ModalShell title={mode === "group" ? "Criar grupo" : "Criar evento"} subtitle={mode === "group" ? "Reúna aventureiros da sua região." : "Planeje um encontro seguro e responsável."} icon={mode === "group" ? Users : CalendarDays} onClose={onClose} notify={notify}><form className="feature-form" onSubmit={submit}><label>Nome<input name="name" required minLength={3} maxLength={100} /></label><label>Descrição<textarea name="description" required minLength={10} maxLength={2000} /></label>{mode === "group" ? <><div className="field-row"><label>Cidade<input name="city" /></label><label>Estado<input name="state" maxLength={2} /></label></div><label>Privacidade<select name="privacy"><option value="public">Público</option><option value="private">Privado — somente convites</option></select></label></> : <><label>Grupo (opcional)<select name="group_id"><option value="">Evento público</option>{groups.filter((group) => group.joined || group.role).map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></label><label>Data e hora<input name="start_at" type="datetime-local" required min={minimumDate} /></label><label>Ponto de encontro<input name="meeting_point" required /></label><div className="field-row"><label>Dificuldade<select name="difficulty"><option value="easy">Fácil</option><option value="moderate">Moderada</option><option value="hard">Difícil</option><option value="expert">Especialista</option></select></label><label>Distância (km)<input name="distance" type="number" min="0" step="0.1" /></label></div><label>Máximo de participantes<input name="max_participants" type="number" min="0" step="1" /></label><label>Equipamentos recomendados<input name="equipment" placeholder="Água, lanterna, bota…" /></label></>}<button className="auth-submit" disabled={loading}>{loading ? "SALVANDO…" : mode === "group" ? "CRIAR GRUPO" : "PUBLICAR EVENTO"}</button></form></ModalShell>;
}

export function GroupDetailPanel({ group, user, onClose, notify, onChanged }: CloseProps & { group: AdventureGroup; user: User | null; onChanged: () => void }) {
  const [loading, setLoading] = useState(false);
  async function toggle() { if (!user) { notify("Entre para participar de grupos"); return; } setLoading(true); try { if (group.joined && group.role === "member") { await leaveGroup(user.id, group.id); notify("Você saiu do grupo"); } else if (!group.joined) { await joinGroup(user.id, group); notify("Bem-vindo ao grupo"); } onChanged(); onClose(); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao atualizar participação"); } finally { setLoading(false); } }
  return <ModalShell title={group.name} subtitle={`${group.city ?? group.state ?? "Brasil"} · ${group.member_count} membros`} icon={Users} onClose={onClose} notify={notify}><div className="group-detail-hero"><span><Users size={32} /></span><h3>{group.privacy === "private" ? <><Lock size={16} /> Grupo privado</> : "Comunidade pública"}</h3><p>{group.description || "Grupo de aventureiros SELVA+."}</p></div><div className="detail-sections"><article><strong>Feed</strong><small>Publicações e atividades compartilhadas pelo grupo.</small></article><article><strong>Eventos</strong><small>Encontros com data, vagas e ponto de encontro.</small></article><article><strong>Trilhas</strong><small>Caminhos recomendados pelos membros.</small></article><article><strong>Moderação</strong><small>Administradores, regras e denúncias da comunidade.</small></article></div><button className="auth-submit" disabled={loading || Boolean(group.role && group.role !== "member")} onClick={() => void toggle()}>{group.role && group.role !== "member" ? `VOCÊ É ${group.role.toUpperCase()}` : group.joined ? "SAIR DO GRUPO" : group.privacy === "private" ? "SOMENTE POR CONVITE" : "PARTICIPAR DO GRUPO"}</button></ModalShell>;
}

export function EventDetailPanel({ event, user, onClose, notify, onChanged }: CloseProps & { event: OutdoorEvent; user: User | null; onChanged: () => void }) {
  const [loading, setLoading] = useState(false);
  async function respond(response: "going" | "maybe" | "not_going") { if (!user) { notify("Entre para responder ao evento"); return; } setLoading(true); try { await respondToEvent(user.id, event.id, response); notify(response === "going" ? "Participação confirmada" : response === "maybe" ? "Marcado como talvez" : "Resposta registrada"); onChanged(); onClose(); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao responder"); } finally { setLoading(false); } }
  return <ModalShell title={event.name} subtitle={new Date(event.start_at).toLocaleString("pt-BR", { dateStyle: "full", timeStyle: "short" })} icon={CalendarDays} onClose={onClose} notify={notify}><div className="event-detail"><div className="event-place"><MapPin size={20} /><div><strong>Ponto de encontro</strong><span>{event.meeting_point || "A confirmar pelo organizador"}</span></div></div><p>{event.description || "Encontro outdoor organizado pela comunidade SELVA+."}</p><div className="trail-detail-metrics"><div><strong>{event.distance ? `${event.distance} km` : "—"}</strong><small>Distância</small></div><div><strong>{event.difficulty || "—"}</strong><small>Nível</small></div><div><strong>{event.participant_count ?? 0}</strong><small>Participantes</small></div><div><strong>{event.max_participants ?? "Livre"}</strong><small>Vagas</small></div></div>{event.recommended_equipment?.length ? <div className="equipment"><strong>Equipamentos recomendados</strong><p>{event.recommended_equipment.join(" · ")}</p></div> : null}<div className="response-buttons"><button disabled={loading} className={event.response === "going" ? "active" : ""} onClick={() => void respond("going")}>Vou</button><button disabled={loading} className={event.response === "maybe" ? "active" : ""} onClick={() => void respond("maybe")}>Talvez</button><button disabled={loading} className={event.response === "not_going" ? "active" : ""} onClick={() => void respond("not_going")}>Não vou</button></div></div></ModalShell>;
}

export function EditProfilePanel({ user, profile, onClose, notify, onSaved }: CloseProps & { user: User; profile: Profile; onSaved: () => void }) {
  const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setLoading(true); try { await updateProfile(user.id, { full_name: String(form.get("full_name")), bio: String(form.get("bio")), city: String(form.get("city")), state: String(form.get("state")), experience_level: String(form.get("experience_level")), profile_visibility: String(form.get("profile_visibility")) as "public" | "private", hide_route_endpoints: form.get("hide_route_endpoints") === "on" }); notify("Perfil atualizado"); onSaved(); onClose(); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao atualizar perfil"); } finally { setLoading(false); } }
  return <ModalShell title="Editar perfil" subtitle="Controle sua identidade e privacidade." icon={UserRound} onClose={onClose} notify={notify}><form className="feature-form" onSubmit={submit}><div className="field-row"><label>Nome<input name="full_name" defaultValue={profile.full_name} required /></label><label>Username de acesso<input name="username" defaultValue={profile.username} readOnly aria-readonly="true" title="O username identifica sua conta e não pode ser alterado." /></label></div><p className="locked-field-note"><Lock size={14} /> O username identifica sua conta e não pode ser alterado.</p><label>Bio<textarea name="bio" maxLength={280} defaultValue={profile.bio ?? ""} /></label><div className="field-row"><label>Cidade<input name="city" defaultValue={profile.city ?? ""} /></label><label>Estado<input name="state" maxLength={2} defaultValue={profile.state ?? ""} /></label></div><div className="field-row"><label>Nível<select name="experience_level" defaultValue={profile.experience_level}><option value="novato">Novato</option><option value="explorador">Explorador</option><option value="aventureiro">Aventureiro</option><option value="mateiro">Mateiro</option><option value="desbravador">Desbravador</option><option value="montanhista">Montanhista</option><option value="expedicionario">Expedicionário</option></select></label><label>Perfil<select name="profile_visibility" defaultValue={profile.profile_visibility}><option value="public">Público</option><option value="private">Privado</option></select></label></div><label className="privacy-check"><input type="checkbox" name="hide_route_endpoints" defaultChecked={profile.hide_route_endpoints} /><span><strong>Ocultar início e fim das rotas</strong><small>Remove aproximadamente 200 m de cada ponta antes de publicar.</small></span></label><button className="auth-submit" disabled={loading}>{loading ? "SALVANDO…" : "SALVAR ALTERAÇÕES"}</button></form></ModalShell>;
}

export function QuickCreatePanel({ user, mode, onClose, notify, onCreated }: CloseProps & { user: User; mode: "post" | "place"; onCreated: () => void }) {
  const [coordinate, setCoordinate] = useState<RouteCoordinate | null>(null); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (mode === "place" && !coordinate) { notify("Capture a localização do lugar"); return; } setLoading(true); try { if (mode === "post") await createPost(user.id, { title: String(form.get("title")), body: String(form.get("body")), location: String(form.get("location")), visibility: String(form.get("visibility")) }); else await createPlace(user.id, { name: String(form.get("name")), category: String(form.get("category")), description: String(form.get("description")), latitude: coordinate![1], longitude: coordinate![0], city: String(form.get("city")), state: String(form.get("state")) }); notify(mode === "post" ? "Publicação criada" : "Local cadastrado e enviado para validação"); onCreated(); onClose(); } catch (error) { notify(error instanceof Error ? error.message : "Não foi possível concluir"); } finally { setLoading(false); } }
  return <ModalShell title={mode === "post" ? "Publicar aventura" : "Cadastrar local"} subtitle={mode === "post" ? "Compartilhe uma história com a comunidade." : "Ajude outros aventureiros a explorar."} icon={mode === "post" ? Trees : MapPin} onClose={onClose} notify={notify}><form className="feature-form" onSubmit={submit}>{mode === "post" ? <><label>Título<input name="title" maxLength={120} placeholder="Nome da aventura" /></label><label>Relato<textarea name="body" required minLength={3} maxLength={5000} placeholder="Conte o que viveu e compartilhe informações úteis." /></label><label>Localização aproximada<input name="location" maxLength={120} /></label><label>Privacidade<select name="visibility"><option value="public">Pública</option><option value="followers">Seguidores</option><option value="private">Somente eu</option></select></label></> : <><label>Nome do lugar<input name="name" required minLength={3} /></label><label>Categoria<select name="category"><option value="waterfall">Cachoeira</option><option value="peak">Pico</option><option value="viewpoint">Mirante</option><option value="camping">Camping</option><option value="park">Parque</option><option value="cave">Caverna</option><option value="river">Rio</option><option value="lake">Lago</option><option value="conservation">Área de conservação</option></select></label><label>Descrição<textarea name="description" maxLength={2000} /></label><div className="field-row"><label>Cidade<input name="city" /></label><label>Estado<input name="state" maxLength={2} /></label></div><CurrentLocation value={coordinate} onChange={setCoordinate} notify={notify} /></>}<button className="auth-submit" disabled={loading}>{loading ? "SALVANDO…" : mode === "post" ? "PUBLICAR" : "CADASTRAR LOCAL"}</button></form></ModalShell>;
}

const REPORT_LABELS: Record<string, string> = { trash: "Lixo", fire: "Queimada/incêndio", fallen_tree: "Árvore caída", landslide: "Deslizamento", blocked_trail: "Trilha bloqueada", erosion: "Erosão", pollution: "Poluição", injured_animal: "Animal ferido", illegal_hunting: "Caça ilegal", danger: "Ponto perigoso", signage: "Falta de sinalização", water_source: "Fonte de água", animal_sighting: "Animal avistado" };

export function EnvironmentMapPanel({ user, onClose, notify, onReport }: CloseProps & { user: User | null; onReport: () => void }) {
  const [reports, setReports] = useState<EnvironmentReport[]>([]); const [loading, setLoading] = useState(true); const [filter, setFilter] = useState("all");
  const refresh = async () => { setLoading(true); try { setReports(await loadEnvironmentReports(user?.id)); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao carregar ocorrências"); } finally { setLoading(false); } };
  useEffect(() => { let active = true; void loadEnvironmentReports(user?.id).then((data) => { if (active) setReports(data); }).catch((error) => notify(error instanceof Error ? error.message : "Falha ao carregar ocorrências")).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [notify, user?.id]);
  const visible = filter === "all" ? reports : reports.filter((report) => report.status === filter);
  const markers = visible.map((report) => ({ id: report.id, label: REPORT_LABELS[report.category] ?? report.category, coordinate: [report.longitude, report.latitude] as RouteCoordinate }));
  async function confirm(report: EnvironmentReport) { if (!user) { notify("Entre para confirmar ocorrências"); return; } try { await toggleReportConfirmation(user.id, report.id, Boolean(report.confirmed_by_me)); await refresh(); notify(report.confirmed_by_me ? "Confirmação removida" : "Ocorrência confirmada"); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao confirmar"); } }
  return <ModalShell title="Mapa Ambiental SELVA+" subtitle="Informação comunitária para preservar e explorar com segurança." icon={Leaf} onClose={onClose} notify={notify}><div className="environment-map"><div className="environment-filters"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>Todas</button><button className={filter === "reported" ? "active" : ""} onClick={() => setFilter("reported")}>Reportadas</button><button className={filter === "confirmed" ? "active" : ""} onClick={() => setFilter("confirmed")}>Confirmadas</button><button className={filter === "resolved" ? "active" : ""} onClick={() => setFilter("resolved")}>Resolvidas</button></div><ExploreMap compact markers={markers} />{loading ? <div className="loading-line"><LoaderCircle className="animate-spin" size={18} /> Atualizando mapa ambiental…</div> : visible.length ? <div className="report-list">{visible.map((report) => <article key={report.id}><span><Leaf size={18} /></span><div><strong>{REPORT_LABELS[report.category] ?? report.category}</strong><p>{report.description}</p><small>{report.status === "reported" ? "Reportado" : report.status === "confirmed" ? "Confirmado pela comunidade" : report.status === "in_review" ? "Em análise" : "Resolvido"} · {report.confirmation_count} confirmações</small></div><button className={report.confirmed_by_me ? "active" : ""} onClick={() => void confirm(report)}><Check size={16} /></button></article>)}</div> : <div className="notification-empty"><ShieldCheck size={28} /><strong>Nenhuma ocorrência neste filtro</strong><span>Isso não garante ausência de riscos. Planeje-se e siga as orientações locais.</span></div>}<button className="auth-submit" onClick={() => { if (!user) notify("Entre para reportar uma ocorrência"); else { onReport(); onClose(); } }}><Plus size={17} /> REPORTAR OCORRÊNCIA</button></div></ModalShell>;
}

export function LiveNotificationPanel({ user, onClose, notify }: CloseProps & { user: User | null }) {
  const [items, setItems] = useState<AppNotification[]>([]); const [loading, setLoading] = useState(Boolean(user));
  useEffect(() => { if (!user) return; let active = true; void loadNotifications(user.id).then((data) => { if (active) setItems(data); }).catch((error) => notify(error instanceof Error ? error.message : "Falha ao carregar notificações")).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [notify, user]);
  async function readAll() { if (!user) return; try { await markNotificationsRead(user.id); setItems((current) => current.map((item) => ({ ...item, read_at: item.read_at ?? new Date().toISOString() }))); } catch (error) { notify(error instanceof Error ? error.message : "Falha ao atualizar notificações"); } }
  return <div className="modal-layer notification-layer" onMouseDown={onClose}><section className="notification-panel" onMouseDown={(event) => event.stopPropagation()}><div className="notification-title"><div><h2>Notificações</h2>{items.some((item) => !item.read_at) ? <button className="read-all" onClick={() => void readAll()}>Marcar como lidas</button> : null}</div><button onClick={onClose}><X size={18} /></button></div>{loading ? <div className="loading-line"><LoaderCircle className="animate-spin" size={18} /> Carregando…</div> : !user ? <div className="notification-empty"><Bell size={29} /><strong>Entre para ver novidades</strong><span>Curtidas, seguidores, eventos e conquistas aparecem aqui.</span></div> : items.length ? <div className="notification-list">{items.map((item) => <article className={!item.read_at ? "unread" : ""} key={item.id}><span>{item.type === "achievement" ? <Trophy size={18} /> : item.type === "event" ? <Clock3 size={18} /> : <Bell size={18} />}</span><div><strong>{item.title}</strong>{item.body ? <p>{item.body}</p> : null}<small>{new Date(item.created_at).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" })}</small></div></article>)}</div> : <div className="notification-empty"><Bell size={29} /><strong>Tudo tranquilo por aqui</strong><span>Suas interações e alertas de trilhas salvas aparecerão nesta central.</span></div>}</section></div>;
}

export function AchievementsPanel({ userId, notify }: { userId: string; notify: Notify }) {
  const [items, setItems] = useState<Achievement[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { void loadAchievements(userId).then(setItems).catch((error) => notify(error instanceof Error ? error.message : "Falha ao carregar conquistas")).finally(() => setLoading(false)); }, [notify, userId]);
  const progress = useMemo(() => items.filter((item) => item.unlocked).length, [items]);
  if (loading) return <div className="skeleton-list"><span /><span /></div>;
  return <div className="achievement-grid">{items.map((item) => <article className={item.unlocked ? "unlocked" : ""} key={item.id}><span>{item.unlocked ? <Trophy size={22} /> : <Lock size={20} />}</span><div><strong>{item.name}</strong><p>{item.description}</p><small>{item.unlocked ? "Conquistada" : `${item.threshold ?? 0} para desbloquear`}</small></div></article>)}{!items.length ? <div className="notification-empty"><Trophy size={29} /><strong>Conquistas em preparação</strong><span>As regras de progressão serão calculadas a partir de atividades reais.</span></div> : <p className="achievement-progress">{progress} de {items.length} conquistas desbloqueadas</p>}</div>;
}
